baseURL = "http://example.org/"
defaultContentLanguage = "en"
languageCode = "en"

title = "d's website"

theme = "custom"

# Automatically generate robots.txt
# enableRobotsTXT = true
[params]
  icon = "/img/fav.png"
  dateForm = "January 2, 2006"

